### ISSUE TITLE
Bibliography format in syllaba

### ISSUE THREAD

**Issue by sammo3182** [svmiller/svm-r-markdown-templates#4]
@svmiller, I appreciate all the rmarkdown templates you provided here! They are very helpful. However, here's a question about the bibliography styles in the syllabus template: why is there always an "In:" for the article bibliography? I didn't find that problem when using your template of academic article, while I didn't find the difference between the two templates in the bibliography part in both latex and rmd files. Do you have any idea where the "In:" comes from---because of the `RefManageR` package?  Thank you.

**Comment by svmiller** [comment]
Hi Yue,

To my chagrin, yes, you get that odd-ball citation format because of `RefManageR`. If you want full bibliographic citations in the middle of a document (a la a syllabus), `RefManageR` is the best R package for it. However, `RefManageR` won't give you the APSA-style citations we all know and love. It gives you just a handful of styles.

There is an alternative to which I allude. `rcrossref` can do this but it requires (to the best of my knowledge) DOI numbers and I'm not a huge fan of fishing for those. It also will not know how to italicize things like the book or journal title. That's a huge drawback. That critique of `rcrossref` true as of my blog post on it last year. My hope is that changes.

**Comment by sammo3182** [comment]
Steven, thank you for the reply! I will go check the `rcrossref`. I also left the same issue under the `RefManageR` repo. Hope the next version of the package may do some improvement.
